### ISSUE TITLE
fix von ein paar Schreibfehlern im pdf

### ISSUE THREAD

**Issue by orgua** [python-fuer-ingenieure/2022-clt-workshop#1]
Folie 15: \\ escaping **\**
Folie 19: "Access much faster **than** to list"
Folie 55: Überschrift sprengt Folie

Ich würde vermutlich das alte String-formatting rauslassen, da fast-strings sie seit 5 jahren komplett ersetzt.

Ansonsten eine gute Einführung zum Weiterempfehlen!

**Comment by cknoll** [comment]
Danke!

Ich habe die Fehler korrigiert und f-strings vorgezogen. Da man aber oft noch alten Code sieht/erbt möchte ich die alten Varianten (als solche gekennzeichnet) noch drin lassen.
